- name: Java installation
  hosts: all
  become: true
  tasks:
    - name: Download the JDK binaries
      get_url:
        url: https://download.java.net/java/GA/jdk18.0.2.1/db379da656dc47308e138f21b33976fa/1/GPL/openjdk-18.0.2.1_linux-x64_bin.tar.gz
        dest: /opt/openjdk-18.0.2.1_linux-x64_bin.tar.gz

    - name: Extract the downloaded file
      command: tar xvf /opt/openjdk-18.0.2.1_linux-x64_bin.tar.gz -C /opt
      
    - name: Update profile
      copy: content="export JAVA_HOME=/opt/jdk-18.0.2.1 \n" dest=/etc/profile.d/java.sh   

    - name: Set the JAVA_HOME in /etc/profile.d/java.sh file
      lineinfile:
        path: /etc/profile.d/java.sh
        state: present
        line: 'export PATH=${JAVA_HOME}/bin:${PATH}'

    - name: Reload /etc/profile file
      shell:
        cmd: source /etc/profile.d/java.sh
