- name: Maven installation
  hosts: all
  become: true
  tasks:
    - name: Download the Maven binaries
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
        dest: /opt/apache-maven-3.9.9-bin.tar.gz 

    - name: Extract Maven
      command: tar xvf /opt/apache-maven-3.9.9-bin.tar.gz -C /opt     

    - name: Update profile
      copy: content="export M2_HOME=/opt/apache-maven-3.9.9 \n" dest=/etc/profile.d/maven.sh   

    - name: Set the M2_HOME in /etc/profile.d/maven.sh file
      lineinfile:
        path: /etc/profile.d/maven.sh
        state: present
        line: 'export PATH=${M2_HOME}/bin:${PATH}'

    - name: Reload /etc/profile file
      shell:
        cmd: source /etc/profile.d/maven.sh
